### ISSUE TITLE
woocommerce 豐收款外掛 下單完成後頁面異常

### ISSUE THREAD

**Issue by Bananacccc** [terrylinooo/wc-sinopac-payment#1]
開啟永豐金流外掛下單後的下單完成畫面就會怪怪的，關掉外掛就會恢復正常

不正常畫面
https://drive.google.com/file/d/1A5QmFU6YGO5lIyVpW7FRbFeRH_NPjRfy/view?usp=sharing

正常畫面
https://drive.google.com/file/d/1cHlFxb33UNHd25X3bpw-c-Rc1wNqcWlg/view?usp=sharing

官網網址 : https://bebahna.com/

**Comment by terrylinooo** [comment]
依您的目錄，可以這樣寫，這樣會依每天日期產生 log 在上層目錄，有發生問題也較好找。
`/home/bebahnac/logs` 目錄要設為可寫入

```
	define( 'WP_DEBUG', true );
	define( 'WP_DEBUG_LOG', '/home/bebahnac/logs/debug_' . date( 'Ymd' ) . '.log' );
	define( 'WP_DEBUG_DISPLAY', false );
```

**Comment by Bananacccc** [comment]
謝謝你😃

**Comment by terrylinooo** [comment]
這個問題也找到並修正，稍候 WordPress 目錄提示更新訊息再更新外掛。
如有其它使用上的問題或建議也歡迎提出。

**Comment by Bananacccc** [comment]
好的，謝謝你的幫忙～
