### ISSUE TITLE
豐收款外掛 信用卡付款/虛擬帳號付款 出現Internal Server Error問題

### ISSUE THREAD

**Issue by Bananacccc** [terrylinooo/wc-sinopac-payment#2]
![Snipaste_2023-05-10_14-27-54](https://github.com/terrylinooo/wc-sinopac-payment/assets/85541286/ca1bd374-a208-4f2f-a2c6-9c1628e26e0c)
![Snipaste_2023-05-10_14-26-17](https://github.com/terrylinooo/wc-sinopac-payment/assets/85541286/7649fdac-7779-4dbc-8fac-f882f02088a2)
[debug_20230510(1).log](https://github.com/terrylinooo/wc-sinopac-payment/files/11438739/debug_20230510.1.log)

上面兩張是出問題的照片
下面是Log
再麻煩您幫忙處理一下了感謝~

**Comment by terrylinooo** [comment]
謝謝提供詳細的 log。我稍後檢查測試，修正並更新後，會再留言通知您。

**Comment by Bananacccc** [comment]
如果是跟一個叫做workat invoice外掛有衝突到的話，再麻煩您留言一下，因為那個是我朋友跟我串的外掛程式，不確定有沒有影響到

**Comment by terrylinooo** [comment]
這個和您的外掛沒有關聯喔。是資料打回網站時，需要解碼要取得 API 的 nonce 時，拿到空值。我在測試環境測沒問題。不知道您是否還會發生?

不過如果是解碼失敗不代表訂單付款失敗喔! 而是回到網站解碼失敗拿不到資料而沒進行下一步記錄訂單狀態和資料的動作。

另外發現 PHP 8.2 有警告訊息，雖不影響，但既然發現了稍候會修正更新。
Nonce 的部分我這邊再看一下如何重現狀況

**Comment by Bananacccc** [comment]
您好，他是發生在我按下付款鈕，連跳轉過去付款頁面都沒有的情況下就出現internal server error的字樣，然後我剛剛再試按一次還是一樣的情況發生。

**Comment by Bananacccc** [comment]
www.bebahna.com
這是出事的網站～ 看還有沒有需要提供給您什麼資訊讓你可以知道發生什麼事

**Comment by terrylinooo** [comment]
我更新了一版，可以試看看是否正常了。
但其實也只是修正了 PHP 版本的警告訊息而已。順帶一問，您的 PHP 版本是?

**Comment by Bananacccc** [comment]
我的是8.2.5
更新完後有出現不一樣的警告了
![Snipaste_2023-05-11_21-11-50](https://github.com/terrylinooo/wc-sinopac-payment/assets/85541286/ad4e4f70-f876-4d9b-bdbf-82f8d3e60f3d)
[debug_20230511.log](https://github.com/terrylinooo/wc-sinopac-payment/files/11452556/debug_20230511.log)
附上今天的log

**Comment by terrylinooo** [comment]
這個要請您寫信給邱先生問看看，你可以直接給他這個討論串。
邱先生 數位支付部-永豐銀行 <ya.chiu@sinopac.com>
我這邊測試環境測試都正常。上面那個訊息是我補上檢查有無 Nonce 的判斷。正式環境拿不到這個值，蠻奇怪。

**Comment by terrylinooo** [comment]
這個要請您寫信給邱先生問看看，你可以直接給他這個討論串。
邱先生 數位支付部-永豐銀行 <ya.chiu@sinopac.com>
我這邊測試環境測試都正常。上面那個訊息是我補上檢查有無 Nonce 的判斷。正式環境拿不到這個值，蠻奇怪。

**Comment by Bananacccc** [comment]
我剛剛把沙盒模式關掉，在試一次他就變回Internal service error，那我還是一樣直接問邱先生嗎

**Comment by terrylinooo** [comment]
那個 Internal service error 的觸發的內容，可以截片段給我嗎?

**Comment by Bananacccc** [comment]
觸發內容是指我怎麼點，讓他出現的嗎

**Comment by Bananacccc** [comment]
![Snipaste_2023-05-11_22-56-50](https://github.com/terrylinooo/wc-sinopac-payment/assets/85541286/f4979b43-fa21-405f-8a85-3f2cba5adf7d)
![Snipaste_2023-05-11_22-57-00](https://github.com/terrylinooo/wc-sinopac-payment/assets/85541286/ba59b66c-45b4-4647-8872-1d577fe8a224)
![Snipaste_2023-05-11_22-57-05](https://github.com/terrylinooo/wc-sinopac-payment/assets/85541286/19d6b748-cf5e-46da-b58c-4c330a80d8a6)
請問是這個嗎
還是指Log裡面的資訊

**Comment by terrylinooo** [comment]
可以把它寄到我的信箱我來看看 terrylin.developer@gmail.com

**Comment by Bananacccc** [comment]
您好  我寄出了

**Comment by terrylinooo** [comment]
看 log 是一開始發請求拿 Nonce 就失敗了，商店代碼是正確的嗎?

**Comment by Bananacccc** [comment]
但我的代碼是填寫永豐給我的說

**Comment by terrylinooo** [comment]
似乎增加新的認證機制，我再回信請您給我另一個資料讓我測試喔。如果您手上有新版文件也寄給我檢查有沒有漏掉的部分

**Comment by terrylinooo** [comment]
![image](https://github.com/terrylinooo/wc-sinopac-payment/assets/11989371/331987c3-493e-4e0d-92c1-0924d4ae72cb)

文件新增的測試環境 API，的確要用 X-KeyID 的 header，用文件裡的 key 測試可以取到 Nonce，但用在正式環境 API 網址不行喔。

![image](https://github.com/terrylinooo/wc-sinopac-payment/assets/11989371/d9edcda1-1f1c-455c-8121-69ebacc000c6)


這個應該是每個用戶有不同的 Key，再請您向技術客服要一下 X-KeyID

稍候我會新開一個 X-KeyID 的欄位，然後更新。
如果您有拿到 X-KeyID，可以先寄信給我測試看看正式環境能否拿到 Nonce

**Comment by Bananacccc** [comment]
我剛剛有跟邱先生確認過了，這個是他們4月底新增的驗證機制，有請他幫我申請這組值了，拿到後我再寄信給您請你幫忙測試，很謝謝你～

陳義喬
0988707458
***@***.***
________________________________
寄件者: Terry L. ***@***.***>
寄件日期: Friday, May 12, 2023 12:00:31 PM
收件者: terrylinooo/wc-sinopac-payment ***@***.***>
副本: Bananacccc ***@***.***>; Author ***@***.***>
主旨: Re: [terrylinooo/wc-sinopac-payment] 豐收款外掛 信用卡付款/虛擬帳號付款 出現Internal Server Error問題 (Issue #2)


[image]<https://user-images.githubusercontent.com/11989371/237865695-331987c3-493e-4e0d-92c1-0924d4ae72cb.png>

文件新增的測試環境 API，的確要用 X-KeyID 的 header，用文件裡的 key 測試可以取到 Nonce，但用在正式環境 API 網址不行喔。

[image]<https://user-images.githubusercontent.com/11989371/237866192-d9edcda1-1f1c-455c-8121-69ebacc000c6.png>

這個應該是每個用戶有不同的 Key，再請您向技術客服要一下 X-KeyID

稍候我會新開一個 X-KeyID 的欄位，然後更新。
如果您有拿到 X-KeyID，可以先寄信給我測試看看正式環境能否拿到 Nonce

**Comment by terrylinooo** [comment]
請問有拿到正式的 x key 了嗎?

**Comment by Bananacccc** [comment]
永豐的人說申請這個要一到兩週
等我拿到大概五月底前了～

**Comment by Bananacccc** [comment]
剛剛拿到了，有發E-Mail給您，再麻煩了感謝～

**Comment by terrylinooo** [comment]
好的。

**Comment by Bananacccc** [comment]
不好意思，目前還沒看到可以更新的訊息

**Comment by terrylinooo** [comment]
晚上下班後更新。我盡量在晚上10點前完成。

**Comment by terrylinooo** [comment]
> 不好意思，目前還沒看到可以更新的訊息

已更新。這此有加上錯誤訊息支援中文。不過因為我沒有正式的帳號，仍沒測試過正式。
測試環境沒問題，再麻煩您看看。

**Comment by Bananacccc** [comment]
您好，我有寫E-Mail將問題回饋給您了

**Comment by Bananacccc** [comment]
您好，剛剛測試下來都很順暢！
但有幾個問題想請問
1. 使用虛擬帳號繳款，按下下單後結帳完成的畫面並未出現，虛擬帳號的付款資訊，但帳戶資訊裡面是有的

2.虛擬帳號繳款，繳款後需要大致上多久時間網站後台才會接收到他完成並轉為處理中呢，因為剛剛信中我提及的這個會改變我發現是我自己手動按到轉為處理中他才變的。

**Comment by terrylinooo** [comment]
看說明書上寫是說，使用者繳款完 豐收款的伺服器  就會通知網站，每10分鐘一次，連續五次。
如果是沙盒模式，會模擬付款，豐收款的伺服器五分鐘後會通知網站。

**Comment by Bananacccc** [comment]
了解，但我網站使用沙盒模式，我已經成立訂單一個小時了，目前尚未變更為處理中

**Comment by terrylinooo** [comment]
好的，我在連同前面的問題檢查完修正，晚上10點前更新。謝謝您的問題回饋。

**Comment by terrylinooo** [comment]
已修正完。

**Comment by Bananacccc** [comment]
您好，有測試過了，兩個問題已確認沒問題！謝謝你的幫忙～
