### ISSUE TITLE
下單後訂單資訊頁面異常

### ISSUE THREAD

**Issue by Bananacccc** [terrylinooo/wc-sinopac-payment#3]
您好，繼上次虛擬帳號付款下單後頁面問題，這次是信用卡付款問題，他下單後會直接跳回網站網站首頁，不會出現訂單資訊。
接著是不確定是否跟這個問題有間接影響到，但我想說告知一下，我用woocommerce內建的貨到付款以及Line pay的外掛付款後他雖然會出現下單後的畫面但訂單資訊卻不見了
再麻煩您了

附上LOG以及其他種付款方式的問題照
![Snipaste_2023-05-22_15-52-54](https://github.com/terrylinooo/wc-sinopac-payment/assets/85541286/4e83cf74-d592-4727-a458-a09eb8e3a6fb)
![Snipaste_2023-05-22_15-53-35](https://github.com/terrylinooo/wc-sinopac-payment/assets/85541286/eb768de5-d23d-4f81-8757-7f2cdd6864b0)
[debug_20230522.zip](https://github.com/terrylinooo/wc-sinopac-payment/files/11528491/debug_20230522.zip)

**Comment by terrylinooo** [comment]
我檢查一下。順便問一下，`workat-invo-plugin/includes/workat-invo.php` 是什麼外掛? 它在 log 裡有很多嚴重錯誤

**Comment by Bananacccc** [comment]
這是我請一個朋友幫忙寫的易發票電子發票的外掛，剛好有遇到一些問題也正在處理中

**Comment by terrylinooo** [comment]
剛更新。

**Comment by Bananacccc** [comment]
好的我測試一下
