### ISSUE TITLE
結帳時出現"The size of the field has reached its limit. Please check out the error log to get details."訊息

### ISSUE THREAD

**Issue by Bananacccc** [terrylinooo/wc-sinopac-payment#4]
您好，我在結帳時有出現這個錯誤訊息"The size of the field has reached its limit. Please check out the error log to get details"，再麻煩你協助了謝謝~

![image](https://github.com/terrylinooo/wc-sinopac-payment/assets/85541286/dffce6f1-315c-434b-92e0-ee0ede31f064)

以下是LOG
[debug_20230527 (1).zip](https://github.com/terrylinooo/wc-sinopac-payment/files/11581766/debug_20230527.1.zip)

**Comment by terrylinooo** [comment]
這邊是商品名稱超過了 API 記錄的限制 60 個字元，商品名稱 82 個字元。
這邊的話，能處理的方法是把送給 API 的文字超過的部位給截除。
另外會補上載入語系檔的語法，讓錯誤訊息以中文顯示

**Comment by Bananacccc** [comment]
原來他有限制字數，那我知道了，再麻煩你了謝謝～

**Comment by Bananacccc** [comment]
您好～這次修改部分要再麻煩您了謝謝

**Comment by Bananacccc** [comment]
您好，我知道這樣對你恨不好意思，但我的網站目前卡在金流無法啟用，真的得再拜託你幫忙了謝謝～

**Comment by terrylinooo** [comment]
已修正喔

**Comment by Bananacccc** [comment]
> 已修正喔

您好，但我這邊尚未有更新的提示
